name: knowledge_graph_api
channels:
  - defaults
dependencies:
  - ca-certificates=2022.07.19
  - certifi=2022.9.24
  - libprotobuf=3.20.1
  - openssl=1.1.1q
  - pip=22.2.2
  - protobuf=3.20.1
  - python=3.8.13
  - setuptools=63.4.1
  - sqlite=3.39.3
  - wheel=0.37.1
  - zlib=1.2.12
  - pip:
    - altair==4.2.0
    - anyio==3.6.2
    - astroid==2.12.12
    - asttokens==2.0.8
    - attrs==22.1.0
    - backcall==0.2.0
    - backports-zoneinfo==0.2.1
    - black==22.10.0
    - blinker==1.5
    - brotli==1.0.9
    - catalogue==2.0.8
    - cffi==1.15.1
    - charset-normalizer==2.1.1
    - colorama==0.4.5
    - commonmark==0.9.1
    - configargparse==1.5.3
    - contourpy==1.0.5
    - coreferee-model-en==1.0.0
    - coverage==6.5.0
    - cycler==0.11.0
    - cymem==2.0.7
    - debugpy==1.6.3
    - decorator==5.1.1
    - en-core-web-lg==3.3.0
    - en-core-web-trf==3.3.0
    - entrypoints==0.4
    - executing==1.1.1
    - fastapi==0.85.1
    - filelock==3.8.0
    - flask==2.2.2
    - flask-basicauth==0.2.0
    - flask-cors==3.0.10
    - flatbuffers==22.9.24
    - fonttools==4.37.4
    - gevent==22.10.1
    - geventhttpclient==2.0.8
    - greenlet==1.1.3.post0
    - h11==0.14.0
    - idna==3.4
    - importlib-metadata==5.0.0
    - iniconfig==1.1.1
    - interchange==2021.0.4
    - ipykernel==6.16.1
    - ipython==8.5.0
    - isort==5.10.1
    - itsdangerous==2.1.2
    - jedi==0.18.1
    - jinja2==3.1.2
    - jsonschema==4.16.0
    - jupyter-client==7.4.3
    - jupyter-core==4.11.2
    - keras==2.10.0
    - kiwisolver==1.4.4
    - langcodes==3.3.0
    - lazy-object-proxy==1.7.1
    - locust==2.12.2
    - markupsafe==2.1.1
    - matplotlib==3.6.1
    - matplotlib-inline==0.1.6
    - mccabe==0.7.0
    - monotonic==1.6
    - msgpack==1.0.4
    - mypy-extensions==0.4.3
    - nest-asyncio==1.5.6
    - numpy==1.23.4
    - packaging==21.3
    - pandas==1.5.1
    - pansi==2020.7.3
    - parso==0.8.3
    - pathspec==0.10.1
    - pathy==0.6.2
    - pickleshare==0.7.5
    - pillow==9.2.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==2.5.2
    - prompt-toolkit==3.0.31
    - pure-eval==0.2.2
    - py2neo==2021.2.3
    - pycparser==2.21
    - pydantic==1.8.2
    - pydeck==0.8.0b4
    - pygments==2.13.0
    - pylint==2.15.4
    - pympler==1.0.1
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - pytest==7.1.3
    - pytest-cov==4.0.0
    - python-dateutil==2.8.2
    - pytz==2022.5
    - pytz-deprecation-shim==0.1.0.post0
    - pyyaml==6.0
    - pyzmq==24.0.1
    - regex==2022.9.13
    - requests==2.28.1
    - rich==12.6.0
    - roundrobin==0.0.4
    - semver==2.13.0
    - six==1.16.0
    - smart-open==5.2.1
    - smmap==5.0.0
    - sniffio==1.3.0
    - spacy-alignments==0.8.6
    - spacy-legacy==3.0.10
    - spacy-loggers==1.0.3
    - spacy-transformers==1.1.7
    - srsly==2.4.5
    - stack-data==0.5.1
    - stanford-openie==1.3.0
    - stanfordnlp==0.2.0
    - starlette==0.20.4
    - streamlit==1.13.0
    - termcolor==2.0.1
    - tokenizers==0.12.1
    - toml==0.10.2
    - tomli==2.0.1
    - tomlkit==0.11.5
    - toolz==0.12.0
    - torch==1.12.1
    - tornado==6.2
    - tqdm==4.64.1
    - traitlets==5.5.0
    - transformers==4.20.1
    - typer==0.4.2
    - typing-extensions==4.4.0
    - tzdata==2022.5
    - tzlocal==4.2
    - urllib3==1.26.12
    - uvicorn==0.19.0
    - validators==0.20.0
    - wasabi==0.10.1
    - watchdog==2.1.9
    - wcwidth==0.2.5
    - werkzeug==2.2.2
    - wget==3.2
    - wrapt==1.14.1
    - zipp==3.9.0
    - zope-event==4.5.0
    - zope-interface==5.5.0
